import { Game, Friend, ShopItem } from '../types';

export const dummyGames: Game[] = [
  {
    id: '1',
    title: 'Space Warriors',
    description: 'Epic space battle game with real-time strategy elements',
    image: '/api/placeholder/300/200',
    genre: 'Strategy',
    players: { current: 124, max: 1000 },
    status: 'waiting',
    duration: '20-30 min',
    difficulty: 'medium',
  },
  {
    id: '2',
    title: 'Quiz Master',
    description: 'Test your knowledge in various categories',
    image: '/api/placeholder/300/200',
    genre: 'Trivia',
    players: { current: 67, max: 500 },
    status: 'waiting',
    duration: '10-15 min',
    difficulty: 'easy',
  },
  {
    id: '3',
    title: 'Card Legends',
    description: 'Strategic card game with unique mechanics',
    image: '/api/placeholder/300/200',
    genre: 'Card',
    players: { current: 45, max: 200 },
    status: 'in-progress',
    duration: '15-25 min',
    difficulty: 'hard',
  },
  {
    id: '4',
    title: 'Racing Thunder',
    description: 'High-speed racing with power-ups and obstacles',
    image: '/api/placeholder/300/200',
    genre: 'Racing',
    players: { current: 89, max: 300 },
    status: 'waiting',
    duration: '5-10 min',
    difficulty: 'medium',
  },
];

export const dummyFriends: Friend[] = [
  {
    id: '1',
    username: 'GamerPro123',
    avatar: '/api/placeholder/50/50',
    status: 'online',
    lastSeen: Date.now(),
    currentGame: 'Space Warriors',
  },
  {
    id: '2',
    username: 'QuizQueen',
    avatar: '/api/placeholder/50/50',
    status: 'away',
    lastSeen: Date.now() - 300000,
  },
  {
    id: '3',
    username: 'CardMaster',
    avatar: '/api/placeholder/50/50',
    status: 'busy',
    lastSeen: Date.now() - 600000,
    currentGame: 'Card Legends',
  },
  {
    id: '4',
    username: 'SpeedDemon',
    avatar: '/api/placeholder/50/50',
    status: 'offline',
    lastSeen: Date.now() - 3600000,
  },
  {
    id: '5',
    username: 'PuzzleMaster',
    avatar: '/api/placeholder/50/50',
    status: 'online',
    lastSeen: Date.now(),
  },
];

export const dummyShopItems: ShopItem[] = [
  {
    id: '1',
    name: 'Cyber Avatar',
    description: 'Futuristic cyberpunk avatar with neon effects',
    image: '/api/placeholder/150/150',
    price: 500,
    currency: 'coins',
    category: 'avatar',
    rarity: 'epic',
    owned: false,
  },
  {
    id: '2',
    name: 'XP Boost',
    description: 'Double XP for 24 hours',
    image: '/api/placeholder/150/150',
    price: 100,
    currency: 'gems',
    category: 'boost',
    rarity: 'common',
    owned: false,
  },
  {
    id: '3',
    name: 'Dragon Theme',
    description: 'Epic dragon-themed UI skin',
    image: '/api/placeholder/150/150',
    price: 1200,
    currency: 'coins',
    category: 'theme',
    rarity: 'legendary',
    owned: false,
  },
  {
    id: '4',
    name: 'Champion Badge',
    description: 'Show off your achievements',
    image: '/api/placeholder/150/150',
    price: 250,
    currency: 'coins',
    category: 'badge',
    rarity: 'rare',
    owned: true,
  },
];
